[package]
authors = ["Raphael Amorim <rapha850@gmail.com>"]
description = "Parser for implementing terminal emulators"
repository = "https://github.com/alacritty/vte"
documentation = "https://docs.rs/vte/"
readme = "README.md"
license = "Apache-2.0 OR MIT"
version = { workspace = true }
name = "copa"
edition = "2021"

[dependencies]
rio-proc-macros = { workspace = true }

[dev-dependencies]
unicode-normalization = "0.1.22"

